//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAdmin
    {
        public int ID { get; set; }
        public string Typepost { get; set; }
        public string Title { get; set; }
        public string Img { get; set; }
        public string Content { get; set; }
    }
}
