//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionfaq
    {
        public int ID { get; set; }
        public string Namequestion { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
