//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex3.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPNEntities : DbContext
    {
        public SPNEntities()
            : base("name=SPNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<HistoryCourse> HistoryCourses { get; set; }
        public virtual DbSet<Historyexam> Historyexams { get; set; }
        public virtual DbSet<PostAdmin> PostAdmins { get; set; }
        public virtual DbSet<Questionfaq> Questionfaqs { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
